openapi: 3.0.3
info:
  title: User Authentication API
  version: 1.0.0
tags:
  - name: Auth
    description: Authentication API
paths:
  /client-api/v1/auth/me:
    get:
      operationId: me
      tags:
        - Auth
      summary: Get current user profile
      description: Get current user profile
      responses:
        200:
          description: Current user profile
          content:
            application/json:
              schema:
                $ref: './shared.yaml/#/components/schemas/UserDTO'
        400:
          $ref: './shared.yaml/#/components/responses/BadRequestException'
        401:
          $ref: './shared.yaml/#/components/responses/UnauthorizedException'
        403:
          $ref: './shared.yaml/#/components/responses/ForbiddenException'
        404:
          $ref: './shared.yaml/#/components/responses/NotFoundException'
        500:
          $ref: './shared.yaml/#/components/responses/InternalServerException'
  /client-api/v1/auth/login:
    post:
      operationId: login
      tags:
        - Auth
      summary: Login with username and password
      description: Login with username and password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginReq'
      responses:
        200:
          description: Login successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginRes'
        400:
          $ref: './shared.yaml/#/components/responses/BadRequestException'
        401:
          $ref: './shared.yaml/#/components/responses/UnauthorizedException'
        403:
          $ref: './shared.yaml/#/components/responses/ForbiddenException'
        404:
          $ref: './shared.yaml/#/components/responses/NotFoundException'
        500:
          $ref: './shared.yaml/#/components/responses/InternalServerException'
  /client-api/auth/summary:
    get:
      summary: Get current user summary
      description: Get current user summary
      operationId: summary
      tags:
        - Auth
      responses:
        200:
          description: User summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSummaryRes'
        400:
          $ref: './shared.yaml/#/components/responses/BadRequestException'
        401:
          $ref: './shared.yaml/#/components/responses/UnauthorizedException'
        403:
          $ref: './shared.yaml/#/components/responses/ForbiddenException'
        404:
          $ref: './shared.yaml/#/components/responses/NotFoundException'
        500:
          $ref: './shared.yaml/#/components/responses/InternalServerException'
  /client-api/v1/forgot-password:
    get:
      operationId: forgotPassword
      tags:
        - Auth
      summary: Forgot password
      description: Forgot password
      parameters:
        - in: query
          name: email
          required: true
          schema:
            type: string
      responses:
        200:
          description: Forgot password email sent
          content:
            application/json: { }
        400:
          $ref: './shared.yaml/#/components/responses/BadRequestException'
        401:
          $ref: './shared.yaml/#/components/responses/UnauthorizedException'
        403:
          $ref: './shared.yaml/#/components/responses/ForbiddenException'
        404:
          $ref: './shared.yaml/#/components/responses/NotFoundException'
        500:
          $ref: './shared.yaml/#/components/responses/InternalServerException'
components:
  schemas:
    LoginReq:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          format: password
        rememberMe:
          type: boolean
    LoginRes:
      type: object
      properties:
        idToken:
          type: string
          format: password
        accessToken:
          type: string
          format: password
        refreshToken:
          type: string
          format: password
    UserSummaryRes:
      type: object
      properties:
        status:
          $ref: './shared.yaml/#/components/schemas/UserStatusEnum'
        privileges:
          type: array
          items:
            $ref: './shared.yaml/#/components/schemas/PrivilegeDTO'